"""Intentional public API for model selection authorization and invocation."""

from app.ai_selection.approval import (
    InvocationApprovalDecision,
    ModelInvocationApprovalRecord,
    ModelInvocationApprovalRequest,
    create_model_invocation_approval_request,
    validate_model_invocation_approval,
)
from app.ai_selection.audit import (
    InvocationAuditStatus,
    ModelInvocationAuditRecord,
    SelectionAuthorizationAuditRecord,
    create_model_invocation_audit_record,
    create_selection_authorization_audit_record,
)
from app.ai_selection.domain import (
    AuthorizationOutcome,
    AuthorizationReason,
    ModelSelectionAuthorizationDecision,
    ModelSelectionContext,
    ResourceType,
    SelectionAction,
    SelectionPolicyFacts,
    SelectionRiskLevel,
    SelectionTargetType,
    TargetTrustBoundary,
)
from app.ai_selection.errors import (
    AuditContractError,
    InvocationAuthorizationError,
    InvocationNotAuthorizedError,
    InvocationPermitMismatchError,
    ModelSelectionError,
    ModelSelectionValidationError,
    SelectionApprovalError,
    SelectionApprovalExpiredError,
    SelectionApprovalMismatchError,
    SelectionApprovalRequiredError,
    SelectionAuthorizationError,
    SelectionPolicyDeniedError,
)
from app.ai_selection.invocation import (
    AuthorizedInvocationPermit,
    ModelInvoker,
    authorize_model_invocation,
    invoke_authorized_model,
)
from app.ai_selection.policy import evaluate_model_selection_policy

__all__ = (
    "AuditContractError",
    "AuthorizationOutcome",
    "AuthorizationReason",
    "AuthorizedInvocationPermit",
    "InvocationApprovalDecision",
    "InvocationAuditStatus",
    "InvocationAuthorizationError",
    "InvocationNotAuthorizedError",
    "InvocationPermitMismatchError",
    "ModelInvocationApprovalRecord",
    "ModelInvocationApprovalRequest",
    "ModelInvocationAuditRecord",
    "ModelInvoker",
    "ModelSelectionAuthorizationDecision",
    "ModelSelectionContext",
    "ModelSelectionError",
    "ModelSelectionValidationError",
    "ResourceType",
    "SelectionAction",
    "SelectionApprovalError",
    "SelectionApprovalExpiredError",
    "SelectionApprovalMismatchError",
    "SelectionApprovalRequiredError",
    "SelectionAuthorizationAuditRecord",
    "SelectionAuthorizationError",
    "SelectionPolicyDeniedError",
    "SelectionPolicyFacts",
    "SelectionRiskLevel",
    "SelectionTargetType",
    "TargetTrustBoundary",
    "authorize_model_invocation",
    "create_model_invocation_approval_request",
    "create_model_invocation_audit_record",
    "create_selection_authorization_audit_record",
    "evaluate_model_selection_policy",
    "invoke_authorized_model",
    "validate_model_invocation_approval",
)
