"""Reusable agent interface and deterministic test implementation."""

from typing import Protocol, runtime_checkable

from app.ai.domain import (
    AgentCapability,
    AgentIdentifier,
    AgentResult,
    AgentStatus,
    AgentTask,
)


@runtime_checkable
class Agent(Protocol):
    """Provider-independent interface implemented by every PolicyOS agent."""

    name: AgentIdentifier
    display_name: str
    description: str
    version: str
    capabilities: frozenset[AgentCapability]
    required_permission: str

    async def execute(self, task: AgentTask) -> AgentResult:
        """Execute a scoped task and return a structured result."""
        ...


class FakeAgent:
    """Deterministic agent for local tests and dependency-injected workflows."""

    def __init__(
        self,
        *,
        name: AgentIdentifier = AgentIdentifier.POLICY_RESEARCH,
        display_name: str = "Fake Policy Research Agent",
        description: str = "Returns a deterministic structured result without network access.",
        version: str = "test-v1",
        capabilities: frozenset[AgentCapability] | None = None,
        required_permission: str = "ai.agent.execute",
    ) -> None:
        self.name = name
        self.display_name = display_name
        self.description = description
        self.version = version
        self.capabilities = capabilities or frozenset({AgentCapability.POLICY_RESEARCH})
        self.required_permission = required_permission

    async def execute(self, task: AgentTask) -> AgentResult:
        return AgentResult(
            task_id=task.task_id,
            agent_id=self.name,
            status=AgentStatus.SUCCEEDED,
            verified_findings=["Deterministic fake finding."],
            analysis=["Deterministic fake analysis."],
            warnings=["This result was generated by a fake agent."],
        )

