"""Intentional public API for normalized provider adapter invocation."""

from app.ai_providers.adapter import ProviderAdapter
from app.ai_providers.domain import (
    AdapterId,
    NormalizedContentKind,
    NormalizedContentPart,
    NormalizedFinishReason,
    NormalizedGenerationParameters,
    NormalizedInvocationFailure,
    NormalizedInvocationKind,
    NormalizedInvocationOutput,
    NormalizedMessage,
    NormalizedMessageRole,
    NormalizedModelInvocationRequest,
    NormalizedModelInvocationResult,
    NormalizedOutputConstraint,
    NormalizedOutputFormat,
    NormalizedOutputPart,
    NormalizedResultStatus,
    NormalizedTokenUsage,
    ProviderAdapterIdentity,
    ProviderInvocationAuditRecord,
    create_provider_invocation_audit_record,
)
from app.ai_providers.errors import (
    InvocationRequestMismatchError,
    ModelProviderMismatchError,
    ProviderAdapterAmbiguousError,
    ProviderAdapterDuplicateError,
    ProviderAdapterError,
    ProviderAdapterMismatchError,
    ProviderAdapterNotFoundError,
    ProviderAdapterValidationError,
    ProviderInvocationFailedError,
    ProviderRegistryMismatchError,
    UnsupportedCapabilityError,
)
from app.ai_providers.invocation import invoke_normalized_model
from app.ai_providers.registry import (
    ProviderAdapterRegistry,
    create_provider_adapter_registry,
)

__all__ = (
    "AdapterId",
    "InvocationRequestMismatchError",
    "ModelProviderMismatchError",
    "NormalizedContentKind",
    "NormalizedContentPart",
    "NormalizedFinishReason",
    "NormalizedGenerationParameters",
    "NormalizedInvocationFailure",
    "NormalizedInvocationKind",
    "NormalizedInvocationOutput",
    "NormalizedMessage",
    "NormalizedMessageRole",
    "NormalizedModelInvocationRequest",
    "NormalizedModelInvocationResult",
    "NormalizedOutputConstraint",
    "NormalizedOutputFormat",
    "NormalizedOutputPart",
    "NormalizedResultStatus",
    "NormalizedTokenUsage",
    "ProviderAdapter",
    "ProviderAdapterAmbiguousError",
    "ProviderAdapterDuplicateError",
    "ProviderAdapterError",
    "ProviderAdapterIdentity",
    "ProviderAdapterMismatchError",
    "ProviderAdapterNotFoundError",
    "ProviderAdapterRegistry",
    "ProviderAdapterValidationError",
    "ProviderInvocationAuditRecord",
    "ProviderInvocationFailedError",
    "ProviderRegistryMismatchError",
    "UnsupportedCapabilityError",
    "create_provider_adapter_registry",
    "create_provider_invocation_audit_record",
    "invoke_normalized_model",
)
