"""Public immutable runtime audit domain API."""

from app.runtime.audit.domain import (
    RuntimeAuditActionReferences,
    RuntimeAuditAuthorityReferences,
    RuntimeAuditContractVersion,
    RuntimeAuditEvent,
    RuntimeAuditEventCategory,
    RuntimeAuditExecutionReferences,
    RuntimeAuditOutcomeReference,
    RuntimeAuditSafeErrorCode,
    RuntimeAuditScope,
    RuntimeAuditTrail,
    RuntimeAuditTrailReference,
)
from app.runtime.audit.errors import (
    RuntimeAuditAppendOnlyError,
    RuntimeAuditCanonicalOrderError,
    RuntimeAuditCategoryError,
    RuntimeAuditChainError,
    RuntimeAuditClassificationError,
    RuntimeAuditError,
    RuntimeAuditReferenceError,
    RuntimeAuditRevisionError,
    RuntimeAuditScopeError,
    RuntimeAuditSequenceError,
    RuntimeAuditTimestampError,
)
from app.runtime.audit.validation import (
    validate_runtime_audit_append,
    validate_runtime_audit_event,
    validate_runtime_audit_event_against_authority,
    validate_runtime_audit_event_against_plan,
    validate_runtime_audit_event_against_registry,
    validate_runtime_audit_event_against_state,
    validate_runtime_audit_trail,
    validate_runtime_audit_trail_reference,
)

__all__ = (
    "RuntimeAuditActionReferences",
    "RuntimeAuditAppendOnlyError",
    "RuntimeAuditAuthorityReferences",
    "RuntimeAuditCanonicalOrderError",
    "RuntimeAuditCategoryError",
    "RuntimeAuditChainError",
    "RuntimeAuditClassificationError",
    "RuntimeAuditContractVersion",
    "RuntimeAuditError",
    "RuntimeAuditEvent",
    "RuntimeAuditEventCategory",
    "RuntimeAuditExecutionReferences",
    "RuntimeAuditOutcomeReference",
    "RuntimeAuditReferenceError",
    "RuntimeAuditRevisionError",
    "RuntimeAuditSafeErrorCode",
    "RuntimeAuditScope",
    "RuntimeAuditScopeError",
    "RuntimeAuditSequenceError",
    "RuntimeAuditTimestampError",
    "RuntimeAuditTrail",
    "RuntimeAuditTrailReference",
    "validate_runtime_audit_append",
    "validate_runtime_audit_event",
    "validate_runtime_audit_event_against_authority",
    "validate_runtime_audit_event_against_plan",
    "validate_runtime_audit_event_against_registry",
    "validate_runtime_audit_event_against_state",
    "validate_runtime_audit_trail",
    "validate_runtime_audit_trail_reference",
)
